source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

use_modular_headers!

target 'IOCipherTests' do
  pod "IOCipher", :path => "../"
  pod 'libsqlfs/SQLCipher', :git => 'https://github.com/ChatSecure/libsqlfs.git', :branch => '1.3.2-chatsecure'
  pod 'SQLCipher', :git => 'https://github.com/ChatSecure/sqlcipher.git', :branch => 'v4.3.0-catalyst'
end

target 'IOCipherServer' do
  pod "IOCipher/GCDWebServer", :path => "../"
end

